language: node_js
node_js:
- lts/*
services:
- redis-server
jobs:
  include:
  - stage: release
    node_js: lts/8
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
env:
  global:
  - secure: gtInHKAvc9+6TT9P1jvLmiI0irbgxyQ/6Qr7dIXMGOvaMmsTK4BsC9+R76LQH4l7IrWbSOCd2YveStveEtzTWlLApeLdzcCVlRnSaAyRknDaU2fqhm9Vgt8fmLVMqEyGgAW9Tc5fqTHeAX3EfDCm4xapcC+RnjzKRAsF+08bWDcHOyTH23czXWLEFLqpPQoGoi8JE5sq1/qmN/HsBJmY7ZL2fgfP2KOh5udziPsD73F5Cr+2szJZPpxxp05lPv9SY9Vp5/HpEcTsOivOrF61iOrMPst/cPH9WiSCOontfnB/ng1Jriotz6pz5Vjc9Wa/9fwZGs4fgvs3SONjzJdtmjbxiLuSsNfyQ5/E4pN3C3YBbMhuVpUdC9QBSOu5ijmK7FaAFhAnUmK6wRnuttRVVeeuhVKZoMaeOsStXkW96224h54NnrL6QWvnhdjMBjv4/mgt4Jvg5lsZK6HOjW8ZQWtNbmC2HkWwf/FxZC/xG2fwAXlKmITCM5h5z2nqFiABA+U+fO5smKhht1Lb24qYNfBWkzAV/2tt4fEKfa7IQxmg4m4BrglXpjZfvOXxrzm2h/1mbaHTHmttrNn9jg5bzyr6j3Oxd8W9XWnnI1j7/n7hrUyAvI+N5ZQxH7WntFBjRqQ/+v+zwHOiWoYKQS4t1JhUOxfWkB0SHDJ9A7mmAjI=
  - secure: 0iJBn8COHKjew2gz90VFDW7m0SmSFJR5TTaozMSmyZluU2wAgKm8Ox1vFryMNsaKbEklabcbQ7EcW32+G7Bd3CjZ4CStJmx3M0rechxidIQ9zw4kQeCyClDEuIv76YIP4+rJaAyWFBhVR/hXFixqtRAVkGpAidhssvD3j1abER28wvCjSvXZEWeTCj8rNDUgzshefPYw5NA3jC5dqYN9Nhb/i+n2DaBDFjKAkCJD4TDTfU051IFTNBGGi/y90D8rGshZwPLZgi2wk3b3K7SNCr8o804+GHYK7AVgvuPlifaDnAYvmxWAlZ5cYCLDPDgvRRGa2zGM5RDUi3mXKqmwLBrWPODYgmZWtv1G7a/PyO4uceMIde0Zuk2iPZzyZxncG19gSAacaMvq2EfDNx8xO8HhaQEMmOwgTdQ8XenzF3ZxoBDB3KHnunESihjl0kSej9ChIycmSqnbFMWm5ZS/cCxunXtckvl0HrK0n+Ep02WkQaxES5KOnTvL7/EoyccYKbi4tgQUhL28eRUDEYnUw0qtPuL9tL5EyL2AZ77630Pk7OnI+RpzXIcGaDzyx1MT/Ji0zH/BOZ34RE+t5O82BqbjpgZ1wSJuPKd6OXMJIZ35SabkUkxWxgHWEq6D/DnGb4F24HGqxXmKRMIKJSbdKWQN8VSGBqqfJiPuX5m+e7U=
